### ISSUE TITLE
DNSCrypt setting changes after each update

### ISSUE THREAD

**Issue by rugk** [bitbeans/SimpleDnsCrypt#50]
After each update the primary resolver is reset to the France one. This is bad. SimpleDnsCrypt should remember the setting of the previous installation.

**Comment by bitbeans** [comment]
Should be fixed for future releases.
I will also add more values to the new config.yaml.

**Comment by CDR-DPH** [comment]
This issue is still occurring. After the latest update v2.0.19 I have had to reconfigure the advanced settings and reselect the resolvers. It took me a while to figure out why none of of my devices could maintain a stable intenret connection - The Global Resolver setting was turned off after the update.
